config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'games#home'
  get 'new', to: 'games#new'
  post 'score', to: 'games#score'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @letters = [*('A'..'Z')].sample(10)
  end

  def score

    @word = params[:word]

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/home.html.erb
<h1>Start to play</h1>
<%= link_to "PLAY", new_path %>
<br>
<br>
<%= link_to "SCORE", score_path %>

app/views/games/new.html.erb
<h1>NEW GAME</h1>
<ul>
<%@letters.each do |letter| %>

<li><%= letter %></li>

<%end%>
</ul>


<h3>what is the Longest word you can find?</h3>

<form action="/score"method="post">
  <input type="text" name="word">
  <input type="submit" value="play">
</form>

<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

<%= link_to "Homepage", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>